"use client";
import {useEffect,useState} from "react";
export default function Provas(){const[exams,setExams]=useState<any[]>([]);const[selected,setSelected]=useState<any|null>(null);const[title,setTitle]=useState("");const[desc,setDesc]=useState("");const[minutes,setMinutes]=useState("");const[passing,setPassing]=useState("60");const[maxAttempts,setMaxAttempts]=useState("1");const[q,setQ]=useState({statement:"",imageUrl:"",points:"1",options:["","","",""],correct:0});const[msg,setMsg]=useState("");
async function load(){const r=await fetch("/api/admin/exams");if(r.ok)setExams(await r.json())}useEffect(()=>{load()},[]);
async function create(){const r=await fetch("/api/admin/exams",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({title,description:desc,passingPercent:Number(passing),timeLimitMinutes:minutes?Number(minutes):null,maxAttempts:Number(maxAttempts)||1})});const j=await r.json();setMsg(r.ok?"Prova criada.":j.error);if(r.ok){setTitle("");setDesc("");load()}}
async function status(id:string,status:string){await fetch("/api/admin/exams",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,status})});load()}
async function addQuestion(){if(!selected)return;const r=await fetch("/api/admin/questions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({examId:selected.id,statement:q.statement,imageUrl:q.imageUrl,points:Number(q.points)||1,alternatives:q.options.map((text,i)=>({text,isCorrect:i===q.correct}))})});const j=await r.json();setMsg(r.ok?"Questão adicionada.":j.error);if(r.ok)setQ({statement:"",imageUrl:"",points:"1",options:["","","",""],correct:0})}
return <main className="wrap"><div className="card"><h1>Banco de provas</h1><p className="muted">Crie, configure e publique os exames sem editar o código.</p><div className="grid"><input className="input" placeholder="Título da prova" value={title} onChange={e=>setTitle(e.target.value)}/><input className="input" placeholder="Descrição" value={desc} onChange={e=>setDesc(e.target.value)}/><input className="input" type="number" min="1" placeholder="Tempo (minutos)" value={minutes} onChange={e=>setMinutes(e.target.value)}/><input className="input" type="number" min="1" max="100" placeholder="Aprovação (%)" value={passing} onChange={e=>setPassing(e.target.value)}/><input className="input" type="number" min="1" placeholder="Máx. tentativas" value={maxAttempts} onChange={e=>setMaxAttempts(e.target.value)}/></div><button className="btn" style={{marginTop:12}} onClick={create}>Criar prova</button>{msg&&<p className="status">{msg}</p>}</div>
{exams.map(e=><section className="card" style={{marginTop:18}} key={e.id}><div style={{display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap"}}><div><h2>{e.title}</h2><p className="muted">{e.description}</p><small>Aprovação: {e.passing_percent??60}% · Tentativas: {e.max_attempts??1}{e.time_limit_minutes?" · "+e.time_limit_minutes+" min":""}</small></div><span className="status">{e.status}</span></div><div className="actions" style={{marginTop:12}}><button className="btn" onClick={()=>setSelected(e)}>+ Adicionar questão</button>{e.status!=="open"&&<button className="btn" onClick={()=>status(e.id,"open")}>Abrir prova</button>}{e.status==="open"&&<button className="btn red" onClick={()=>status(e.id,"closed")}>Fechar prova</button>}</div></section>)}
{selected&&<div className="card" style={{marginTop:18}}><div className="actions" style={{justifyContent:"space-between"}}><h2>Nova questão — {selected.title}</h2><button className="btn red" onClick={()=>setSelected(null)}>Fechar</button></div><textarea className="textarea" placeholder="Enunciado" value={q.statement} onChange={e=>setQ({...q,statement:e.target.value})}/><input className="input" style={{marginTop:10}} placeholder="URL opcional da imagem" value={q.imageUrl} onChange={e=>setQ({...q,imageUrl:e.target.value})}/>{q.options.map((v,i)=><div className="actions" style={{marginTop:10}} key={i}><input type="radio" checked={q.correct===i} onChange={()=>setQ({...q,correct:i})}/><input className="input" placeholder={"Alternativa "+String.fromCharCode(65+i)} value={v} onChange={e=>{const a=[...q.options];a[i]=e.target.value;setQ({...q,options:a})}}/></div>)}<input className="input" style={{marginTop:10}} type="number" min="1" placeholder="Pontos" value={q.points} onChange={e=>setQ({...q,points:e.target.value})}/><button className="btn" style={{marginTop:12}} onClick={addQuestion}>Salvar questão</button></div>}</main>}