"use client";import {useEffect,useMemo,useState} from "react";import {useRouter} from "next/navigation";
export default function ExamForm({examId,questions,timeLimitMinutes,attempted,initialAttemptId,initialStartedAt}:{examId:string;questions:any[];timeLimitMinutes:number|null;attempted:boolean;initialAttemptId:string|null;initialStartedAt:string|null}){const[a,setA]=useState<Record<string,string>>({});const[err,setErr]=useState("");const[busy,setBusy]=useState(false);const[starting,setStarting]=useState(!initialAttemptId&&!attempted);const[attemptId,setAttemptId]=useState(initialAttemptId);const[startedAt,setStartedAt]=useState(initialStartedAt);const[seconds,setSeconds]=useState(0);const router=useRouter();const answered=useMemo(()=>Object.keys(a).length,[a]);
async function start(){setStarting(true);const r=await fetch("/api/exams/start",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({examId})});const j=await r.json();if(!r.ok){setErr(j.error||"Não foi possível iniciar.");setStarting(false);return}setAttemptId(j.attemptId);setStartedAt(j.startedAt);setStarting(false)}
useEffect(()=>{if(starting&&!attemptId&&!attempted)start()},[]);
useEffect(()=>{if(!startedAt||!timeLimitMinutes)return;const end=new Date(startedAt).getTime()+Number(timeLimitMinutes)*60000;const tick=()=>setSeconds(Math.max(0,Math.ceil((end-Date.now())/1000)));tick();const id=setInterval(tick,1000);return()=>clearInterval(id)},[startedAt,timeLimitMinutes]);
useEffect(()=>{if(seconds===0&&startedAt&&timeLimitMinutes&&!busy){send(true)}},[seconds]);
async function send(auto=false){if(busy||!attemptId)return;setBusy(true);setErr("");const r=await fetch("/api/exams/submit",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({examId,attemptId,answers:a})});const j=await r.json();if(!r.ok){setErr(j.error||"Não foi possível enviar.");setBusy(false);return}router.push("/resultado/"+j.attemptId)}
const mm=String(Math.floor(seconds/60)).padStart(2,"0"),ss=String(seconds%60).padStart(2,"0");
if(attempted)return <div className="card"><span className="status warn">TENTATIVA ENCERRADA</span><p>Você já atingiu o limite de tentativas deste exame.</p></div>;
if(starting&&!attemptId)return <div className="card"><p>Preparando sua tentativa segura...</p></div>;
return <div><div className={"examBar "+(seconds>0?"":"danger")}><div><b>Tempo restante</b><strong>{timeLimitMinutes?mm+":"+ss:"Sem limite"}</strong></div><div><b>Respondidas</b><strong>{answered}/{questions.length}</strong></div></div>{questions.map((q:any,i:number)=><div className="question" key={q.id}><div className="questionNumber">QUESTÃO {i+1}</div><h3>{q.statement}</h3>{q.image_url&&<img src={q.image_url} alt="" style={{maxWidth:"100%",maxHeight:420,objectFit:"contain",margin:"12px 0",borderRadius:12}}/>}{(q.alternatives??[]).sort((x:any,y:any)=>x.order_index-y.order_index).map((o:any)=><label className={"option examOption "+(a[q.id]===o.id?"selected":"")} key={o.id}><input type="radio" name={q.id} value={o.id} checked={a[q.id]===o.id} onChange={e=>setA({...a,[q.id]:e.target.value})}/><span>{o.text}</span></label>)}</div>)}{err&&<p className="status danger">{err}</p>}<div className="examSubmit"><button className="btn" disabled={busy||!attemptId||seconds===0} onClick={()=>send(false)}>{busy?"Enviando...":"Finalizar exame"}</button><span className="muted">{answered} de {questions.length} questões respondidas</span></div></div>}